Repository iml1111/SejongSQL, pull requests merged in 2022-05, with the labels that each got.

#32 [feat-31] Query Parser 버그 수정
  sejongsql/module/query_analyzer/mysql/query_parser.py
Labels: Bugfix

#34 [feat-33] Sejong Auth API 구현
  sejongsql/app_main/models/user.py
  sejongsql/app_main/serializer.py
  sejongsql/app_main/urls.py
  sejongsql/app_main/views/envs.py
  sejongsql/app_main/views/users.py
Labels: Feat

#40 [feat-38] 멀티프로세싱 기반 비동기 큐 구현
  sejongsql/app_main/urls.py
  sejongsql/app_main/views/async_sample.py
  sejongsql/module/async_queue/__init__.py
  sejongsql/module/async_queue/async_queue.py
  sejongsql/module/async_queue/base.py
  sejongsql/module/async_queue/task.py
Labels: Feat

#42 [feat-41] SQL Query Parser 테이블명 반환 수정
  sejongsql/module/query_analyzer/mysql/query_parser.py
Labels: Feat

#50 [feat-49] 문제집 생성 API 수정
  sejongsql/app_main/views/pgroup.py
Labels: Feat

#54 [feat-16] 문제 생성,수정,삭제,반환 API 구현
  .gitignore
  sejongsql/app_main/admin.py
  sejongsql/app_main/migrations/__init__.py
  sejongsql/app_main/models/__init__.py
  sejongsql/app_main/models/problem.py
  sejongsql/app_main/serializer.py
  sejongsql/app_main/urls.py
  sejongsql/app_main/views/problems.py
Labels: Feat

#55 [refac-46] 도커 컴포즈 구조 수정
  Dockerfile
  requirements.txt
  sejongsql/config/settings/base.py
Labels: Chore, Refac, dependencies

#61 [feat-60] SQL File 저장 경로 수정
  sejongsql/module/environ.py
Labels: Feat

#64 [feat-63] 워커 이슈 트래거 API 구현
  sejongsql/app_main/urls.py
  sejongsql/app_main/views/async_sample.py
  sejongsql/app_main/views/management.py
  sejongsql/module/async_queue/async_queue.py
Labels: Feat

#66 [feat-53] Env 생성, 삭제 api 수정
  sejongsql/app_main/migrations/0001_initial.py
  sejongsql/app_main/migrations/0002_env_account_name_env_account_pw.py
  sejongsql/app_main/models/env.py
  sejongsql/app_main/views/envs.py
  sejongsql/module/environ.py
Labels: Feat

#71 [feat-70] 세종대학교 구성원 인증 API 수정
  sejongsql/app_main/models/user.py
  sejongsql/app_main/views/users.py
Labels: Feat

#73 [feat-70] 세종대학교 구성원 인증 API 수정
  sejongsql/app_main/models/user.py
  sejongsql/app_main/views/users.py
Labels: Feat

#81 [feat-80] Env 생성 parameter 변경
  sejongsql/app_main/views/envs.py
  sejongsql/app_main/views/problems.py
  sejongsql/module/environ.py
Labels: Feat

#83 [Feat-69] AsyncQueue 전역 exception 기능 구현
  assets/Dockerfile.multi
  assets/docker-compose.yml
  assets/portainer.sh
  assets/ssql.env
  sejongsql/module/async_queue/async_queue.py
Labels: Feat, Refac

#85 [feat-84] 분반 내 사용자 검색 API 수정
  sejongsql/app_main/views/classes.py
Labels: Feat

#88 [feat-87] 분반 정보 및 목록 반환 API 수정
  sejongsql/app_main/serializer.py
  sejongsql/app_main/views/classes.py
Labels: Feat

#91 [feat-76] 교수 검색, 분반 내 사용자 검색 API 수정
  sejongsql/app_main/urls.py
  sejongsql/app_main/views/classes.py
  sejongsql/app_main/views/users.py
Labels: Feat

#98 [feat-97] 특정 문제집 반환 및 수정 API
  sejongsql/app_main/serializer.py
  sejongsql/app_main/urls.py
  sejongsql/app_main/views/pgroup.py
Labels: Feat

#95 [feat-94] Select Query Firewall 모듈 추가
  sejongsql/module/query_analyzer/mysql/select_query_firewall/__init__.py
  sejongsql/module/query_analyzer/mysql/select_query_firewall/firewall.py
  sejongsql/module/query_analyzer/mysql/select_query_firewall/parser.py
  sejongsql/module/query_analyzer/mysql/select_query_firewall/traverse.py
Labels: Feat

#100 [feat-75] 문제 관련 API 구현
  sejongsql/app_main/serializer.py
  sejongsql/app_main/urls.py
  sejongsql/app_main/views/problems.py
  sejongsql/module/environ.py
Labels: Feat

#102 [Feat-101] SELECT Query Validator 업그레이드 적용
  sejongsql/module/query_analyzer/mysql/query_validator.py
  sejongsql/module/query_analyzer/mysql/select_query_firewall/traverse.py
Labels: Bugfix, Feat
