Repository iml1111/SejongSQL, pull requests merged in 2022-04, with the labels that each got.

#10 [feat-8] 도커라이징 및 배포 자동화 세팅 구축
  .github/workflows/production-deploy.yml
  Dockerfile
  README.md
  assets/docker-compose.yml
  sejongsql/config/settings/production.py
Labels: Bugfix, Feat, Chore

#9 [feat-7] 사용자 API 구현
  sejongsql/app_main/admin.py
  sejongsql/app_main/migrations/0001_initial.py
  sejongsql/app_main/models/__init__.py
  sejongsql/app_main/models/classes.py
  sejongsql/app_main/models/env.py
  sejongsql/app_main/models/log.py
  sejongsql/app_main/models/problem.py
  sejongsql/app_main/models/user.py
  sejongsql/app_main/serializer.py
  sejongsql/app_main/urls.py
  sejongsql/app_main/views/users.py
  sejongsql/module/response.py
  sejongsql/module/validator.py
Labels: Feat

#19 [feat-6] SELECT Query Validator 구현
  sejongsql/module/query_analyzer/__init__.py
  sejongsql/module/query_analyzer/mysql/__init__.py
  sejongsql/module/query_analyzer/mysql/query_validator.py
  sejongsql/module/query_analyzer/uri.py
Labels: Feat, Refac

#21 [feat-14] 분반 API 구현
  .gitignore
  sejongsql/app_main/admin.py
  sejongsql/app_main/migrations/0001_initial.py
  sejongsql/app_main/migrations/__init__.py
  sejongsql/app_main/models/__init__.py
  sejongsql/app_main/models/classes.py
  sejongsql/app_main/models/sample.py
  sejongsql/app_main/models/user.py
  sejongsql/app_main/serializer.py
  sejongsql/app_main/urls.py
  sejongsql/app_main/views/classes.py
  sejongsql/app_main/views/sample.py
  sejongsql/app_main/views/users.py
  sejongsql/config/settings/base.py
  sejongsql/module/decorator.py
Labels: Feat, Refac

#23 [feat-15] 문제집 API 구현
  sejongsql/app_main/models/problem.py
  sejongsql/app_main/serializer.py
  sejongsql/app_main/urls.py
  sejongsql/app_main/views/pgroup.py
Labels: Feat

#25 [feat-18] Validator 구현
  sejongsql/app_main/views/users.py
  sejongsql/module/exceptions.py
  sejongsql/module/rules.py
  sejongsql/module/validator.py
Labels: Feat

#27 [feat-26] .sql 파서 구현
  sejongsql/module/query_analyzer/mysql/query_parser.py
Labels: Feat

#30 [feat-29] Query Parser 테이블 반환 방식 변경
  sejongsql/module/query_analyzer/mysql/query_parser.py
Labels: Feat
