Repository iml1111/SejongSQL, pull requests merged in 2022-06, with the labels that each got.

#104 [feat-96] 권한 관련 API 구현 및 검색 API 수정
  sejongsql/app_main/migrations/0004_userbelongauth.py
  sejongsql/app_main/models/__init__.py
  sejongsql/app_main/models/user.py
  sejongsql/app_main/serializer.py
  sejongsql/app_main/urls.py
  sejongsql/app_main/views/classes.py
  sejongsql/app_main/views/users.py
Labels: Feat

#111 [feat-110] 수정용 문제 반환 API 구현
  sejongsql/app_main/serializer.py
  sejongsql/app_main/urls.py
  sejongsql/app_main/views/problems.py
Labels: Feat

#113 [bugfix-105] env 분반 생성 시, 관리자 검증
  sejongsql/app_main/views/envs.py
Labels: Bugfix

#114 [bugfix-109] mysql 에러 구문 변경 및 특수 공백문자 제거
  sejongsql/app_main/views/problems.py
  sejongsql/module/environ.py
Labels: Bugfix

#115 [feat-17] 통계 반환 API 구현
  sejongsql/app_main/serializer.py
  sejongsql/app_main/urls.py
  sejongsql/app_main/views/status.py
Labels: Feat

#122 [feat-121] 문제집 모델 activate 필드 추가 및 문제집 활성화 로직 변경
  sejongsql/app_main/migrations/0005_problemgroup_activate.py
  sejongsql/app_main/models/problem.py
  sejongsql/app_main/serializer.py
  sejongsql/app_main/views/pgroup.py
Labels: Feat

#125 [feat-124] 문제 API 활성화 체크 방식 변경
  sejongsql/app_main/serializer.py
  sejongsql/app_main/views/problems.py
  sejongsql/module/environ.py
Labels: Feat

#129 [bugfix-128] mysql 에러구문 변환시 조건 추가
  sejongsql/module/environ.py
Labels: Bugfix

#131 [bugfix-130] 분반 반환시, class_id 고정되는 문제
  sejongsql/app_main/views/classes.py
Labels: Bugfix

#136 bugfix: 특정 분반 사용자 목록 반환 교수 제외 로직 변경
  sejongsql/app_main/views/classes.py
Labels: Bugfix

#138 [bugfix-137] env에 연결된 모든 테이블 반환
  sejongsql/app_main/views/problems.py
  sejongsql/module/environ.py
Labels: Bugfix

#141 [bugfix-134] Select Query Firewall 모듈 @ Operator 차단하지 못하는 버그 수정
  sejongsql/module/query_analyzer/mysql/select_query_firewall/traverse.py
Labels: Bugfix

#142 [bugfix-140] 비활된 주차 반환 및 env 삭제시 문제 반환
  sejongsql/app_main/serializer.py
  sejongsql/app_main/views/classes.py
  sejongsql/app_main/views/pgroup.py
  sejongsql/app_main/views/problems.py
Labels: Bugfix

#145 [feat-144] 통계 paging 및 이름 rule 적용
  sejongsql/app_main/views/status.py
  sejongsql/app_main/views/users.py
  sejongsql/module/rules.py
Labels: Feat

#148 [feat-146] race contion을 이용한 동시추가 방어
  sejongsql/app_main/views/classes.py
Labels: Bugfix, Feat

#149 [feat-147] id, pw 공백 rule 추가
  sejongsql/app_main/views/users.py
  sejongsql/module/rules.py
Labels: Feat

#154 [bugfix-153] 테이블명 parsing error
  sejongsql/module/environ.py
Labels: Bugfix

#155 [feat-152] 비밀번호 수정 rule 적용
  sejongsql/app_main/views/users.py
Labels: Feat

#159 [feat-158] QA 적용
  sejongsql/app_main/views/problems.py
  sejongsql/app_main/views/users.py
  sejongsql/module/environ.py
Labels: Bugfix, Feat
